[package]
name = "pipeline"
version = "0.1.0"
authors = ["nooberfsh <nooberfsh@gmail.com>"]

[dependencies]
uuid = { version = "0.5", features = ["v4"] }
log = "0.4"
futures = "0.1"

[dev-dependencies]
env_logger = "0.4"
